In [1]:
print("Tere, maailm")

Tere, maailm

In [14]:
import os
os.getcwd()

'C:\\Users\\ukuja\\PycharmProjects\\RAM0620'

In [15]:
import pandas as pd

In [10]:
myData = { 'people': ["Margus", "Anna", "Rosin"], "years" : ["10", "22", "12"]}

In [11]:
DataFrame1 = pd.DataFrame(myData)
print(DataFrame1)

   people years
0  Margus    10
1    Anna    22
2   Rosin    12

In [18]:
df = pd.read_csv("C:/Users/ukuja/PycharmProjects/RAM0620/Jupyter lab/väike_log.txt", parse_dates=["date"])
status_order = ["Healthy", "Warning", "Failure"]
df["health_status"] = pd.Categorical(df["health_status"], categories = status_order, ordered = True)
display(df.head())

,date,hostname,os,uptime_hours,adobe_runtime_minutes,cpu_usage_percent,memory_usage_percent,disk_free_gb,health_status,ticket_opened
0,2026-02-01,EDGE-001,Windows XP,13.62,11.87,44.3,70.3,211.8,Healthy,False
1,2026-02-01,EDGE-002,Fedora 41,13.36,9.98,9.5,24.0,11.8,Failure,True
2,2026-02-01,EDGE-003,Ubuntu 24.04,19.84,14.51,58.0,39.8,100.1,Healthy,False
3,2026-02-01,EDGE-004,Windows 11,21.02,1.06,44.8,95.5,188.2,Failure,True
4,2026-02-01,EDGE-005,Windows XP,13.02,4.63,47.3,57.9,282.7,Healthy,False

In [19]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   300 non-null    datetime64[us]
 1   hostname               300 non-null    str
 2   os                     300 non-null    str
 3   uptime_hours           300 non-null    float64
 4   adobe_runtime_minutes  300 non-null    float64
 5   cpu_usage_percent      300 non-null    float64
 6   memory_usage_percent   300 non-null    float64
 7   disk_free_gb           300 non-null    float64
 8   health_status          300 non-null    category
 9   ticket_opened          300 non-null    bool
dtypes: bool(1), category(1), datetime64[us](1), float64(5), str(2)
memory usage: 49.3 KB

In [20]:
df.dtypes

date                     datetime64[us]
hostname                            str
os                                  str
uptime_hours                    float64
adobe_runtime_minutes           float64
cpu_usage_percent               float64
memory_usage_percent            float64
disk_free_gb                    float64
health_status                  category
ticket_opened                      bool
dtype: object

In [21]:
df.isna().sum()

date                     0
hostname                 0
os                       0
uptime_hours             0
adobe_runtime_minutes    0
cpu_usage_percent        0
memory_usage_percent     0
disk_free_gb             0
health_status            0
ticket_opened            0
dtype: int64

In [22]:
df.select_dtypes(include=["number"]).describe()

,uptime_hours,adobe_runtime_minutes,cpu_usage_percent,memory_usage_percent,disk_free_gb
count,300.000000,300.000000,300.000000,300.000000,300.000000
mean,17.930333,9.238433,50.226000,55.505000,169.102333
std,4.340514,5.640801,23.303405,19.769376,105.961058
min,3.950000,0.040000,2.700000,3.000000,8.000000
25%,15.022500,4.597500,34.125000,41.700000,88.400000
50%,18.360000,8.950000,45.300000,53.300000,170.200000
75%,21.287500,13.372500,61.325000,69.475000,236.575000
max,24.000000,22.780000,99.900000,100.000000,480.000000

In [23]:
df["health_status"].value_counts().reindex(df["health_status"].cat.categories)

Healthy    172
Warning     63
Failure     65
Name: count, dtype: int64

In [24]:
df["date"].min(),df["date"].max()

(Timestamp('2026-02-01 00:00:00'), Timestamp('2026-03-02 00:00:00'))

In [25]:
df[["cpu_usage_percent","memory_usage_percent","disk_free_gb"]].agg(["min","max"])

     cpu_usage_percent  memory_usage_percent  disk_free_gb
min                2.7                   3.0           8.0
max               99.9                 100.0         480.0

In [26]:
print(df["cpu_usage_percent"].head())

0    44.3
1     9.5
2    58.0
3    44.8
4    47.3
Name: cpu_usage_percent, dtype: float64

In [27]:
print(df[["cpu_usage_percent", "memory_usage_percent"]].tail())

     cpu_usage_percent  memory_usage_percent
295               26.9                  30.9
296               41.0                  69.8
297               38.2                  19.5
298               65.4                  45.1
299               91.8                  61.2

In [28]:
display(df.iloc[250:255])

,date,hostname,os,uptime_hours,adobe_runtime_minutes,cpu_usage_percent,memory_usage_percent,disk_free_gb,health_status,ticket_opened
250,2026-02-26,EDGE-001,Windows XP,12.55,10.71,53.4,56.0,262.7,Healthy,False
251,2026-02-26,EDGE-002,Fedora 41,19.36,11.99,81.9,59.4,81.4,Warning,False
252,2026-02-26,EDGE-003,Ubuntu 24.04,16.97,15.68,63.1,53.9,152.5,Healthy,False
253,2026-02-26,EDGE-004,Windows 11,20.31,7.10,24.8,43.2,23.5,Warning,False
254,2026-02-26,EDGE-005,Windows XP,22.03,9.97,43.7,70.2,267.9,Healthy,False

In [29]:
is_failure = df["health_status"] == "Failure"
print(df.loc[is_failure, ["date", "hostname", "health_status", "cpu_usage_percent"]].head())

         date  hostname health_status  cpu_usage_percent
1  2026-02-01  EDGE-002       Failure                9.5
3  2026-02-01  EDGE-004       Failure               44.8
5  2026-02-01  EDGE-006       Failure               99.1
8  2026-02-01  EDGE-009       Failure               16.3
11 2026-02-02  EDGE-002       Failure               53.1

In [30]:
high_cpu = df["cpu_usage_percent"] >= 80
print(df.loc[is_failure & high_cpu, ["date", "hostname", "cpu_usage_percent"]].head())

         date  hostname  cpu_usage_percent
5  2026-02-01  EDGE-006               99.1
43 2026-02-05  EDGE-004               93.0
47 2026-02-05  EDGE-008               92.1
57 2026-02-06  EDGE-008               98.9
72 2026-02-08  EDGE-003               92.2

In [31]:
display(df.iloc[0]) #esimene rida

date                     2026-02-01 00:00:00
hostname                            EDGE-001
os                                Windows XP
uptime_hours                           13.62
adobe_runtime_minutes                  11.87
cpu_usage_percent                       44.3
memory_usage_percent                    70.3
disk_free_gb                           211.8
health_status                        Healthy
ticket_opened                          False
Name: 0, dtype: object

In [32]:
display(df.iloc[100:111]) #algusest 10e

,date,hostname,os,uptime_hours,adobe_runtime_minutes,cpu_usage_percent,memory_usage_percent,disk_free_gb,health_status,ticket_opened
100,2026-02-11,EDGE-001,Windows XP,6.97,3.21,95.8,33.4,215.0,Failure,False
101,2026-02-11,EDGE-002,Fedora 41,21.85,1.28,8.7,53.9,8.0,Failure,True
102,2026-02-11,EDGE-003,Ubuntu 24.04,12.00,4.40,31.3,69.1,191.0,Healthy,False
103,2026-02-11,EDGE-004,Windows 11,20.06,2.12,44.2,33.3,306.0,Healthy,False
104,2026-02-11,EDGE-005,Windows XP,15.57,7.88,88.2,59.6,165.9,Warning,True
105,2026-02-11,EDGE-006,Ubuntu 24.04,19.34,6.42,39.7,55.0,102.2,Healthy,False
106,2026-02-11,EDGE-007,Ubuntu 24.04,23.96,5.32,70.9,68.1,151.5,Healthy,False
107,2026-02-11,EDGE-008,Windows 11,19.17,17.38,54.9,74.1,164.3,Healthy,False
108,2026-02-11,EDGE-009,Ubuntu 24.04,16.07,0.32,85.5,83.9,156.6,Warning,True
109,2026-02-11,EDGE-010,Ubuntu 24.04,15.36,0.64,92.6,25.8,220.2,Failure,True
110,2026-02-12,EDGE-001,Windows XP,14.64,2.29,45.9,58.5,195.5,Healthy,False

In [33]:
filter1 = (df["hostname"] == "EDGE-005") & df["date"].between("2026-02-10", "2026-02-15")

In [34]:
print(df.loc[filter1,["hostname", "date", "memory_usage_percent"]].head())

     hostname       date  memory_usage_percent
94   EDGE-005 2026-02-10                  72.3
104  EDGE-005 2026-02-11                  59.6
114  EDGE-005 2026-02-12                  78.5
124  EDGE-005 2026-02-13                  49.4
134  EDGE-005 2026-02-14                  86.5

In [35]:
filter2 = df["hostname"].isin(["EDGE-005", "EDGE-009"]) & (df["health_status"] >= "Warning")
print(df.loc[filter2, "date":"memory_usage_percent"].head())

         date  hostname            os  uptime_hours  adobe_runtime_minutes  \
8  2026-02-01  EDGE-009  Ubuntu 24.04         16.10                  12.04
24 2026-02-03  EDGE-005    Windows XP         19.60                  17.63
28 2026-02-03  EDGE-009  Ubuntu 24.04         20.18                   0.81
48 2026-02-05  EDGE-009  Ubuntu 24.04         15.45                  13.31
94 2026-02-10  EDGE-005    Windows XP         24.00                   6.42

    cpu_usage_percent  memory_usage_percent
8                16.3                  98.5
24               49.1                  69.3
28               48.3                  90.7
48                9.9                  96.8
94               37.5                  72.3